<?php

namespace App\Exports;

use App\FormDetails;
use Maatwebsite\Excel\Concerns\FromCollection;
use App\FormBoolean;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\WithHeadings;


class FormExport implements FromCollection, WithHeadings
{
    /**
     * @return \Illuminate\Support\Collection
     */

    public function collection()
    {
        $forms = DB::table('form_details')
            ->join('form_booleans', 'form_booleans.form_details_id', '=', 'form_details.id')
            ->select('form_details.id',
            'form_details.site_ref',
            'form_details.site_type',
            'form_details.date_and_time',
            'form_details.cluster_enginner',
            'form_details.check_man',
            'form_details.site_with_single_generator',
            'form_details.s_n_generator1',
            'form_details.s_n_generator2',
            'form_details.gen1_type',
            'form_details.gen1_size',
            'form_details.gen2_type',
            'form_details.gen2_size',
            'form_details.gen1_status',
            'form_details.gen2_status',
            'form_details.gen1_rhours',
            'form_details.gen2_rhours',
            'form_booleans.gen1_oil',
            'form_details.gen1_oil_hours',
            'form_booleans.gen2_oil',
            'form_details.gen2_oil_hours',
            'form_booleans.gen1_oil_filter',
            'form_booleans.gen2_oil_filter',
            'form_booleans.gen1_oil_filter',
            'form_booleans.gen2_oil_filter',
            'form_booleans.gen1_lift_pump_filter',
            'form_booleans.gen2_lift_pump_filter',
            'form_booleans.gen1_air_filter',
            'form_booleans.gen2_air_filter',
            'form_booleans.gen1_clean',
            'form_booleans.gen2_clean',
            'form_booleans.gen1_radiator_clean',
            'form_booleans.gen2_radiator_clean',
            'form_booleans.gen1_sensor_status',
            'form_booleans.gen2_sensor_status',
            'form_booleans.gen1_charging_issue',
            'form_booleans.gen2_charging_issue',
            'form_booleans.engine_smoke_ok',
            'form_booleans.engine_smoke_white',
            'form_booleans.engine_smoke_black',
            'form_booleans.oil_leakage_ok',
            'form_booleans.oil_filter',
            'form_booleans.oil_pump',
            'form_booleans.oil_drain',
            'form_booleans.oil_valve_cover',
            'form_booleans.oil_seal',
            'form_booleans.water_leakage_ok',
            'form_booleans.water_leakage_radiator',
            'form_booleans.water_leakage_fils',
            'form_booleans.water_radiator_join',
            'form_booleans.water_pump',
            'form_booleans.fuel_leakage_ok',
            'form_booleans.fuel_nozzle',
            'form_booleans.fuel_pipe_valve',
            'form_booleans.fuel_tube',
            'form_booleans.fuel_filter',
            'form_details.fuel_tank_cm',
            'form_booleans.fuel_tank_piping',
            'form_booleans.fuel_tank_pipe_valves',
            'form_booleans.fuel_tank_drain',
            'form_booleans.ats_board_clean',
            'form_booleans.mdb_board_clean',
            'form_details.plc_board_status',
            'form_details.ats_contactor_status',
            'form_details.relay_timer_status',
            'form_details.mdb_board_status',
            'form_details.surge_arrestor_status',
            'form_details.phase_failure_status',
            'form_details.rbs_cb_status',
            'form_details.rbs_heat_exchanger',
            'form_booleans.rbs1_battery_set',
            'form_booleans.rbs2_battery_sets',
            'form_details.rbs_door_sensor',
            'form_details.rbs_dummy',
            'form_details.clu_status',
            'form_details.fire_extiguisher_status',
            'form_details.flexible_tube_status',
            'form_details.lights_status',
            'form_details.emergency_lights_status',
            'form_details.no_of_psus_pdus',
            'form_booleans.commercial_power',
            'form_details.commercial_power_amperes',
            'form_details.commercial_power_cpreadings',
            'form_booleans.external_power',
            'form_details.external_power_amperes',
            'form_booleans.exceeding_power',
            'form_details.exceeding_power_amperes',
            'form_details.ac_status',
            'form_details.ac_type',
            'form_details.ac_size',
            'form_details.ac_control_status',
            'form_booleans.ac_clean',
            'form_booleans.site_clean',
            'form_booleans.alarm_door_sensor_ok',
            'form_booleans.alarm_door_sensor_not_ok',
            'form_booleans.alarm_generator_ok',
            'form_booleans.alarm_generator_not_ok',
            'form_booleans.external_alarm_status_ok',
            'form_booleans.external_alarm_status_not_ok',
            'form_details.comments',
            'form_details.general_notes'
               )
            ->get();

        return $forms;
    }
    
    public function headings(): array
    {
        return [
            "#",
            'Site Ref',
            'Site Type',
            'Date and Time',
            'Cluster Engineer',
            'Checkman',
            'Site With Single Gen',
            'S/N Gen1',
            'S/N Gen2',
            'Gen1 Type',
            'Gen1 Size',  
            'Gen2 Type',            
            'Gen2 Size',            
            'Gen1 Status',            
            'Gen2 Status',            
            'Gen1 R.Hours',            
            'Gen2 R.Hours',            
            'Gen1 Oil',            
            'Gen1 Oil Hours',            
            'Gen2 Oil',            
            'Gen2 Oil Hours',            
            'Gen1 Oil Filter',            
            'en2 Oil Filter',            
            'Gen1 Fuel Filter',            
            'Gen2 Fuel Filter',            
            'Gen1 Lift Pump Filter',            
            'Gen2 Lift Pump Filter',            
            'Gen1 Air Filter',            
            'Gen2 Air Filter',            
            'Gen1 Clean',            
            'Gen2 Clean',            
            'Gen1 Radiator Clean',            
            'Gen2 Radiator Clean',            
            'Gen1 Sensors Status',            
            'Gen2 Sensors Status',            
            'Gen1 Charging Issue',            
            'Gen2 Charging Issue',            
            'Engine Smoke Ok',            
            'Engine Smoke White',            
            'Engine Smoke Black',            
            'Oil Leakage Ok',            
            'Oil Leakage Filter',            
            'Oil Leakage Case',            
            'Oil Leakage Pump',            
            'Oil Leakage drain',            
            'Oil Valve Cover',            
            'Oil Leakage Seal',            
            'Water Leakage Ok',            
            'Water Leakage Radiator',            
            'Water Leakage Fils',            
            'Water Leakage Radiator Join',            
            'Water Leakage Pump',            
            'Fuel Leakage Ok',            
            'Fuel Leakage Nozzle',            
            'Fuel Leakage Pipe Valve',            
            'Fuel Leakage Tube',            
            'Fuel Leakage Filter',            
            'Fuel Tank CM',            
            'Fuel Tank Piping',            
            'Fuel Tank Pipe Valves',            
            'Fuel Tank Drain',            
            'ATS Board Clean',            
            'MDB Board Clean',            
            'ATS Board Status',            
            'PLC Board Status',            
            'ATS Contactor Status',            
            'Relay And Timer Status Status',            
            'MDB Board Status',            
            'Surge Arrestor Status',            
            'Phase Failure Status',            
            'RBS CB Status',            
            'RBS Heat Exchanger',            
            'RBS Battery 1 Set',            
            'RBS Battery 2 sets',            
            'RBS Door Sensor',            
            'RBS Dummy',            
            'CLU Status',            
            'Fire Extiguisher',            
            'Flexible Tube Status',            
            'Lights Status',            
            'Emergency Lights Status',            
            'No of PSUs/PDUs',            
            'Commercial Power',            
            'Commercial Power Amperes',            
            'Commercial Power CP Readings',            
            'External Power',            
            'External Power Amperes',            
            'Exceeding Power',      
            'Exceeding Power Amperes',            
            'AC Status',            
            'AC Type',            
            'AC Size',            
            'AC Control Status',            
            'AC Control clean',            
            'AC Control Site Clean',            
            'Alarm Door Sensor Clean OK',            
            'Alarm Door Sensor Clean Not OK',            
            'Alarm Generator OK',            
            'Alarm Generator Not OK',            
            'External Alarm Status Ok',            
            'External Alarm Status Not Ok',      
            'Comments',            
            'General Notes'
        ];
    }
}